### ISSUE TITLE
Show text - text missing ($10 bounty)

### ISSUE THREAD

**Issue by aphadeon** [avarisc/OpenGame.exe#6]
I have spent hours trying to figure out where the text from Show Text is gone to.  It's not visible, but is rendering.  Text works almost everywhere else, using the same functions - not sure why in this case it is invisible.

I have a bounty on this issue of $10. First person to submit a pull request that fixes it can collect the bounty.  It's not much, but figured we might as well make this fun.

**Comment by felixjones** [comment]
This is because the font building method is being called inside a Ruby fiber thread, not the thread that the OpenGL context exists on (Main thread) when the font is part of a Message box.

Set a breakpoint on "internal void SyncBitmap()" in Bitmap.cs then open a Message box and you'll see the GL calls are on a different thread.

Moving this call onto the Main thread should fix this issue.

**Comment by felixjones** [comment]
Completed with pull request https://github.com/avarisc/OpenGame.exe/pull/24

![text_working](https://cloud.githubusercontent.com/assets/1824671/8966423/3b7ec9f4-3629-11e5-8bb2-e22d9a8d806d.png)
